### ISSUE TITLE
Improve the state of the CI on the release branches

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#12163]
### Description

We don’t have a clear picture of how stable our CI is on release branches because we don’t make changes to them often. As a result, we don’t get enough feedback about their status. This issue will track efforts to assess the current state of the CI on release branches and identify any improvements needed.

### Tasks:
- [ ] Set up periodic CI runs for each supported release branch
  - [ ] https://github.com/kumahq/kuma/pull/12164
  - [x] https://github.com/kumahq/kuma/pull/12234 (master)
  - [x] https://github.com/kumahq/kuma/pull/12149 (release-2.9)
  - [x] https://github.com/kumahq/kuma/pull/12231 (release-2.8)
  - [x] https://github.com/kumahq/kuma/pull/12232 (release-2.7)
  - [x] https://github.com/kumahq/kuma/pull/12233 (release-2.6)
  - [ ] https://github.com/kumahq/kuma/pull/12256
