### ISSUE TITLE
Policies 2.0 Tracker

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#5194]
### Description

This issue is designed to track progress and completion of the new policies & selector work happening in 2.0 / 2.1:

- [x] Traffic Permission https://github.com/kumahq/kuma/pull/4666 / https://github.com/kumahq/kuma/issues/4790
- [x] Traffic Trace https://github.com/kumahq/kuma/issues/4732 https://github.com/kumahq/kuma/issues/5033
- [x] Traffic Log https://github.com/kumahq/kuma/issues/4733 https://github.com/kumahq/kuma/issues/4979
- [x] Timeout https://github.com/kumahq/kuma/pull/5094 https://github.com/kumahq/kuma/issues/5267
- [x] Rate Limit https://github.com/kumahq/kuma/issues/4740 https://github.com/kumahq/kuma/issues/5361 https://github.com/kumahq/kuma/issues/5381
- [x] Health Check https://github.com/kumahq/kuma/issues/4735 https://github.com/kumahq/kuma/issues/5380 https://github.com/kumahq/kuma/issues/5446
- [x] Circuit Breaker https://github.com/kumahq/kuma/issues/4736 https://github.com/kumahq/kuma/issues/5451 https://github.com/kumahq/kuma/issues/5453
- [X] Retry https://github.com/kumahq/kuma/issues/4738 https://github.com/kumahq/kuma/issues/5495 https://github.com/kumahq/kuma/issues/5494 **docs missing** https://github.com/kumahq/kuma-website/issues/1188
- [x] Proxy Template https://github.com/kumahq/kuma/issues/4737 https://github.com/kumahq/kuma/issues/5563 https://github.com/kumahq/kuma/issues/5564
- [x] OPA https://github.com/Kong/kong-mesh/issues/1590 https://github.com/Kong/kong-mesh/issues/2269 https://github.com/Kong/kong-mesh/issues/2270
- [x] Fault Injection https://github.com/kumahq/kuma/issues/4734
- [x] Traffic Route https://github.com/kumahq/kuma/issues/4743 https://github.com/kumahq/kuma/issues/5470
