### ISSUE TITLE
Support Multicluster and Hybrid environments

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#760]
### Summary

Based on [multicluster.md](https://github.com/Kong/kuma/blob/master/docs/proposals/multicluster.md)

This is the master issue to hold all the relevant tasks for the implementation.

 - [x] Global/Local config infrastructure (kumactl install) #766
     - [x] Provide a basic testing facility (related to #773) 
     - [x] Block Dataplane API/ XDS/SDS in Global #767
     - [x] Block all but the Dataplane API and GUI in Local #768
     - [x] Register Local(s) to Global #769
 - [x] Support DNS resolver in Kuma CP #764
     - [x] Pod converter for Kuma IP Outbound #765
     - [x] DNS persistence
 - [x] Destructure service tag on Kubernetes #800
     - [x] Support all tags in sources and destinations #801
 - [x] Introduce Ingress Dataplane #778
    - [x] Kuma DP deployment #777
    - [x] Generate inbounds of Ingress Automatically #775
    - [x] Generate XDS for Ingress Dataplane #776
    - [x] Outbound XDS generation
 - [x] Mark Dataplanes/Ingress with cluster tag in Local #802
 - [x] Global/Local Synchronisation
     - [x] XDS server(Global)/client(Local) for Kuma Resources (Policies/Ingress) #803
     - [x] Local CP leader election #805 
    - [x] XDS client(Local) used to sync the databases #804
     - [x] XDS server(Local)/client(Global) for Dataplane/Ingress synchronization #806
 - [x] Secure the Global/Local communication (?) #807
 - [x] Documentation

**Comment by nickolaev** [comment]
Released in 0.6.0. Any follow-ups will be in separate issues.
